name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Checkout du code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances
      - name: Install dependencies
        run: yarn install

      # Étape 3 : Construire le projet
      - name: Build the project
        run: yarn build

      # Étape 4 : Démarrer le serveur de prévisualisation
      - name: Start production preview server
        run: yarn preview &
        env:
          PORT: 4173

      # Étape 5 : Exécuter Lighthouse CI Action
      - name: Run Lighthouse CI
        uses: treosh/lighthouse-ci-action@v8
        with:
          urls: http://localhost:4173/
          uploadArtifacts: temporary-public-storage
