name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install dependencies
        run: yarn install

      - name: Start Build
        run: yarn build

      - name: Check bundle size
        run: yarn check:size

      - name: run Lighthouse CI
        run: |
          yarn add -g @lhci/cli@0.14.x
          lhci autorun
