name: Comment Edited Trigger

on:
  issue_comment:
    types:
      - edited

jobs:
  log-comment:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Log "Hello World"
      - name: Print Hello World
        run: echo "Hello World"
