name: Preview Deployment

on:
  pull_request:
    branches:
      - main

jobs:
  deploy-preview:
    runs-on: ubuntu-latest

    steps:
      # Étape 1 : Cloner le dépôt
      - name: Checkout repository
        uses: actions/checkout@v3

      # Étape 2 : Installer les dépendances
      - name: Install dependencies
        run: yarn install

      # Étape 3 : Construire le projet
      - name: Build the project
        run: yarn build

      # Étape 4 : Déployer une URL de prévisualisation avec Vercel
      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          npm install -g vercel
          vercel pull --yes --environment=preview
          vercel build
          vercel deploy --prebuilt --token $VERCEL_TOKEN
