name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on: [pull_request]
permissions:
  issues: write
  pull-requests: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      deployed_url: ${{ steps.deploy_step.outputs.deployed_url}}
    environment:
      name: Preview
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy_step
        run: |
          URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | grep -o 'https://.*\.vercel\.app')
          echo "Deployed URL: $URL"
          echo "deployed_url=$URL" >> "$GITHUB_OUTPUT"

  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    env:
      URL: ${{needs.deploy.outputs.deployed_url}}
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        id: lighthouse_audit
        with:
          urls: ${{needs.deploy.outputs.deployed_url}}
          uploadArtifacts: true
          temporaryPublicStorage: true
          budgetPath: './budget.json'
      - uses: actions/github-script@v7
        with:
          script: |
            console.log(context)
            console.log(${{ steps.lighthouse_audit.outputs.manifest }})
            const test = "Hello !!!";
            await github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `**Welcome**, new contributor!
                ${test}
                Please make sure you've read our [contributing guide](CONTRIBUTING.md) and we look forward to reviewing your Pull request shortly ✨`
            })
