name: GitHub Actions Vercel Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.step1.outputs.test }}
      output2: ${{ steps.step2.outputs.test }}
      url: ${{ steps.deploy_step.outputs.url}}
    environment:
      name: Preview
    steps:
      - uses: actions/checkout@v3
      - name: Install Vercel CLI
        run: npm install --global vercel@canary
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        id: deploy_step
        run: |
          URL=$(vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} | grep -o 'https://.*\.vercel\.app')
          echo "Deployed URL: $URL"
          echo "url=$URL" >> "$GITHUB_OUTPUT"
      - id: step1
        run: echo "test=hello" >> "$GITHUB_OUTPUT"
      - id: step2
        run: echo "test=world" >> "$GITHUB_OUTPUT"

  lighthouse:
    needs: deploy
    runs-on: ubuntu-latest
    steps:
      - env:
          OUTPUT1: ${{needs.deploy.outputs.output1}}
          OUTPUT2: ${{needs.deploy.outputs.output2}}
          URL: ${{needs.deploy.outputs.url}}
        run: echo "$URL hoho"
    # steps:
    #   - name: Display Deployment URL
    #     run: echo "${{ steps.deploy_step.outputs.url }}"
